---
- hosts: all
  remote_user: root
  tasks:
    - name: install Apache service
      yum: name=httpd  state=present
    - name: copy config file
      file: src=/tmp/httpd/httpd.conf dest=/etc/httpd/conf/
      notify: restart httpd
    - name: start apache service
      service: name=httpd state=started enabled=yes

  handlers:
    - name: restart httpd     # 调用notify的名字
      service: name=httpd state=restarted
